# SPARQL Query
# Finds all breast implant devices with smooth shell surfaces
# 
# RETURNS deviceID superClassLabel classLabel

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX BIO:  <http://www.purl.obolibrary.org/BIO/>


SELECT ?superClass ?superClassLabel ?class ?classLabel
WHERE {
    ?superClass rdfs:label ?superClassLabel .
    ?class rdfs:subClassOf ?superClass .
    ?class rdfs:label ?classLabel .
    ?has_shell_surface rdfs:label "has shell surface" .
    ?smooth_shell_surface rdfs:label "smooth shell surface" .

    # ?deviceIDprop rdfs:label "deviceID" .

    ?class rdfs:subClassOf* ?restriction .
    ?restriction owl:onProperty ?has_shell_surface;
                 owl:someValuesFrom ?smooth_shell_surface .
    # ?class ?deviceIDprop ?deviceID .
}
